/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import static org.junit.Assert.*;

public class AppTest {
    
    @Test public void testBookToString() {
        Quote[] quotesArray = FileReadAndWrite.fileToReaderObject();
        String expectedTest = "Quote: “I am good, but not an angel. I do sin, but I am not the devil. I am just a small girl in a big world trying to find someone to love.” - Author: Marilyn Monroe";
        System.out.println(quotesArray[0].toString());
        assertEquals("Our expected text should equal the book.toString method", expectedTest, quotesArray[0].toString());
    }

    @Test public void testRandomize() {

        Quote[] quotesArray = FileReadAndWrite.fileToReaderObject();
        String test1 = Randomizer.generateQuoteAndAuthor(quotesArray);
        String test2 = Randomizer.generateQuoteAndAuthor(quotesArray);
        assertFalse("The two strings returned by the randomizer should be unique.", test1.equals(test2));
    }

    @Test public void testRandomizeHarder() {
        Quote[] quotesArr = FileReadAndWrite.fileToReaderObject();

        String test1 = Randomizer.generateQuoteAndAuthor(quotesArr);
        String test2 = Randomizer.generateQuoteAndAuthor(quotesArr);
        String test3 = Randomizer.generateQuoteAndAuthor(quotesArr);
        String test4 = Randomizer.generateQuoteAndAuthor(quotesArr);
        String test5 = Randomizer.generateQuoteAndAuthor(quotesArr);

        assertFalse("The two strings returned by the randomizer should be unique.", test1.equals(test2));
        assertFalse("The two strings returned by the randomizer should be unique.", test1.equals(test3));
        assertFalse("The two strings returned by the randomizer should be unique.", test1.equals(test4));
        assertFalse("The two strings returned by the randomizer should be unique.", test1.equals(test5));

    }

}
